name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
  node-version:
    required: true
    description: NodeJS version to use
    default: "20.x"
  working-dir:
    required: true
    description: The working directory of the application
    default: .
  target-env:
    required: false
    description: '"dev" or "prod". Controls whether dev dependencies are installed'
runs:
  using: composite
  steps:
  - name: Setup NodeJS version
    uses: actions/setup-node@v3
    with:
      node-version: ${{ inputs.node-version }}

  - name: Cache Node modules
    uses: actions/cache@v3
    with:
      path: ${{ inputs.working-dir }}/node_modules
      key: node-modules-${{ inputs.target-env }}-${{ hashFiles(format('{0}/package-lock.json', inputs.working-dir)) }}

      restore-keys: |
        node-modules-${{ inputs.target-env }}-

  - name: Install Node dependencies
    shell: bash
    run: |
      if [[ "${{ inputs.target-env }}" == "prod" ]]; then
        npm ci --omit=dev
      else
        npm ci
      fi
    working-directory: ${{ inputs.working-dir }}
