name: explorando
on:
#   push:
  workflow_dispatch:
#   pull_request:
#   schedule:
#     - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
            echo "Triggered by: ${{ github.event_name }}"
