name: caching
on:
    workflow_dispatch:
        inputs:
            using-cache:
                type: boolean
                description: Usar cache de dependencias ?
                default: true
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./my-react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: "~> 20.x"
            - name: Download Dependencies
              uses: actions/cache@v3
              if: ${{inputs.using-cache}}
              id: cache
              with:
                path: my-react-app/node_modules
                key:  dependencies-node-modules-${{ hashFiles('my-react-app/package-lock.json')}}
                
            - name: Install dependencies
              if: ${{!steps.cache.outputs.cache-hit}}
              run: npm ci
            
            - name: Testing
              run: npm run test
            
            - name: Building
              run: npm run build
            
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"