name: 15 - Working with Matrices

on: 
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: 16.x
            os: ubuntu-latest
          - node-version: 21.x
            os: ubuntu-latest
            tag: experimental
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    steps:
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit 1
        

      - name: Perform some tests
        continue-on-error: true
        run: |
          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
          sleep 10

      - name: Upload test results
        run: echo "Uploading test results"
  include-example:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shape: [suare, circle]
        color: [red, green]
        size: [small, large]
        include:
        - opacity: 50
        - color: red
          opacity: 75
        - shape: circle
          opacity: 100
        - color: red
          shape: triangle
        exclude:
        - opacity: 75
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{matrix.size}}
    steps:
        - name: Dummy step
          run: |
            echo "${{ matrix.color }}-${{ matrix.shape }}-${{matrix.size}}"
