name: 17 - 2 - Custom Actions - JS
on:
    workflow_dispatch:
run-name: 17 - 2 - Custom Actions - JS
jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/js-dependency-update
           