name: "18 - 1 - Reusable Workflows - Reusable Definition"

on:
  workflow_call:
    inputs:
      target-directory:
        description: "The target directory to use"
        required: true
        type: string
    outputs:
      build-status:
        description: "The status of the build process"
        value: ${{jobs.deploy.outputs.build-status}}
      url:
        description: "The URL of the deployed version"
        value: ${{jobs.deploy.outputs.url}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        id: build
        run: |
          echo "Building using directory ${{ inputs.target-directory }}"
          echo "::set-output name=build-status::success"

      - name: Deploy
        id: deploy
        run: |
          echo "Deploying build artifacts"
          echo "::set-output name=url::https://www.google.com"
