name: 19 - 1 - Managing Concurrency
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
    example-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Print ref
          run: echo "Git ref is ${{ github.ref }}"
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Ping URL
              uses: ./.github/actions/docker-ping-url/action.yaml
              with:
                url: www.google.com
                max-trials: 20
                delay: 5